last_build_profile = "aws=RELEASE,gnat_native=RELEASE,gnatcoll=RELEASE,gnatcoll_minimal=RELEASE,gnatprove=RELEASE,make=RELEASE,openssl=RELEASE,paperclips_core=RELEASE,paperclips_server=DEVELOPMENT,xmlada=RELEASE"

