/* Configuration for paperclips_core generated by Alire */
#ifndef PAPERCLIPS_CORE_CONFIG_H
#define PAPERCLIPS_CORE_CONFIG_H

#define CRATE_VERSION "0.1.0"
#define CRATE_NAME "paperclips_core"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "arch"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
