#!/usr/bin/env python3
"""
Self-host Google Fonts woff2 files and emit @font-face CSS.

Downloads the Google css2 API stylesheet (not committed — it hotlinks
gstatic), keeps only the subsets we want, fetches those woff2 files into
this directory, and writes:

  - <family>.self.css          local-url @font-face blocks (audit / rebuild)
  - ../src/styles/fonts.css concatenated app stylesheet with /fonts/ URLs

Skipping vietnamese / greek / greek-ext keeps the bundle small while still
covering salvaged game-data translations (French = latin-ext, Russian =
cyrillic) per PAPERCLIPS §12.
"""
from __future__ import annotations

import os
import re
import urllib.request

# subset identifier → start of the unicode-range line used to recognise it.
SUBSET_KEYS = {
    "latin": "U+0000-00FF",
    "latin-ext": "U+0100-02BA",
    "cyrillic-ext": "U+0460-052F",
    "cyrillic": "U+0301, U+0400-045F",
}

# google css2 family query → (slug, subsets to keep)
FAMILIES: list[tuple[str, str, list[str]]] = [
    ("League+Gothic", "league-gothic", ["latin", "latin-ext"]),
    ("Oswald:wght@200..700", "oswald", ["latin", "latin-ext", "cyrillic-ext", "cyrillic"]),
    (
        "Alegreya+Sans:wght@400;500;700",
        "alegreya-sans",
        ["latin", "latin-ext", "cyrillic-ext", "cyrillic"],
    ),
    ("Alegreya:ital,wght@0,400..800;1,400..700", "alegreya", ["latin", "latin-ext"]),
    ("Special+Elite", "special-elite", ["latin", "latin-ext"]),
    ("IM+Fell+English:ital@0;1", "im-fell-english", ["latin", "latin-ext"]),
]

UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)

FONT_FACE_RE = re.compile(r"@font-face\s*\{[^}]*\}", re.DOTALL)

STACKS = """
/*
 * Font stacks — every face carries a system fallback (spec §12).
 * Use these --font-* tokens, not raw family names.
 */
:root {
  --font-head: 'League Gothic', 'Oswald', 'Arial Narrow', 'Helvetica Neue', sans-serif;
  --font-label: 'Oswald', 'Arial Narrow', system-ui, sans-serif;
  --font-body: 'Alegreya Sans', system-ui, -apple-system, 'Segoe UI', sans-serif;
  --font-serif: 'Alegreya', Georgia, 'Iowan Old Style', 'Palatino Linotype', serif;
  --font-typewriter: 'Special Elite', 'Courier New', monospace;
  --font-epigraph: 'IM Fell English', Georgia, 'Iowan Old Style', serif;
}
"""


def detect_subset(block: str) -> str | None:
    m = re.search(r"unicode-range:\s*([^;]+);", block)
    if not m:
        return None
    rng = m.group(1).strip()
    for key, marker in SUBSET_KEYS.items():
        if rng.startswith(marker):
            return key
    return None


def rewrite_src(block: str, local_path: str) -> str:
    return re.sub(
        r"src:\s*url\([^)]+\)\s*format\('woff2'\)",
        f"src: url(\"{local_path}\") format('woff2')",
        block,
        count=1,
    )


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def process(
    family_param: str,
    family_slug: str,
    keep_list: list[str],
    base: str,
) -> str:
    css_url = f"https://fonts.googleapis.com/css2?family={family_param}&display=swap"
    print(f"== {family_slug} ==")
    print(f"  GET {css_url}")
    css = fetch(css_url).decode("utf-8")

    keep = set(keep_list)
    seen: set[str] = set()
    out_blocks: list[str] = []
    for block in FONT_FACE_RE.findall(css):
        subset = detect_subset(block)
        if subset is None or subset not in keep:
            continue
        sm = re.search(r"font-style:\s*(\w+)", block)
        wm = re.search(r"font-weight:\s*([^;]+)", block)
        style = sm.group(1) if sm else "normal"
        weight = (wm.group(1).strip() if wm else "400").replace(" ", "-")
        m = re.search(r"url\((https://[^)]+)\)", block)
        if not m:
            continue
        remote_url = m.group(1)
        local_name = f"{family_slug}-{style}-{weight}-{subset}.woff2"
        if local_name in seen:
            continue
        seen.add(local_name)
        dst = os.path.join(base, local_name)
        if not os.path.exists(dst):
            print(f"  download {local_name}")
            with open(dst, "wb") as fh:
                fh.write(fetch(remote_url))
            print(f"    -> {os.path.getsize(dst)} bytes")
        else:
            print(f"  keep {local_name}")
        out_blocks.append(rewrite_src(block, f"./{local_name}"))

    header = (
        f"/* Self-hosted font: {family_slug}.\n"
        f"   Source: Google Fonts css2 API, rewritten offline.\n"
        f"   Subsets kept: {', '.join(keep_list)}.\n"
        f"   GENERATED by scripts/build-fonts.py — do not hand-edit. */\n\n"
    )
    self_path = os.path.join(base, f"{family_slug}.self.css")
    with open(self_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("\n".join(out_blocks))
        f.write("\n")
    print(f"  wrote {self_path} ({len(out_blocks)} faces)")

    # App stylesheet uses absolute /fonts/ URLs (served from public/).
    return "\n".join(out_blocks).replace('url("./', 'url("/fonts/')


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    base = os.path.normpath(os.path.join(here, "..", "public", "fonts"))
    parts: list[str] = [
        "/* GENERATED by scripts/build-fonts.py (offline).\n"
        "   Every @font-face points at a woff2 served from /fonts/ under\n"
        "   frontend/public/fonts/. Per-family licenses: public/fonts/LICENSE.md.\n"
        "   System fallbacks per spec §12. Do not hand-edit; re-run scripts/build-fonts.py. */\n"
    ]
    for family_param, slug, subsets in FAMILIES:
        parts.append(process(family_param, slug, subsets, base))
        parts.append("")

    parts.append(STACKS)
    out = os.path.normpath(os.path.join(here, "..", "src", "styles", "fonts.css"))
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
        if not parts[-1].endswith("\n"):
            f.write("\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
