import { describe, expect } from "vitest";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
// The SC-C5 generator library ships without type declarations (plain .mjs);
// the two consumed functions are exercised structurally by the cases below.
// @ts-expect-error -- no declaration file for skill/contract-lib.mjs
import { enumerateOperationIds, parseOpenApi } from "../../../skill/contract-lib.mjs";
import { testCase } from "../../src/test-case.js";

// ---------------------------------------------------------------------------
// SC-O7 capability-parity oracle (frozen against the Wave 2 capability
// manifest — skill/api-reference/capability-manifest.json, generated by
// skill/generate-capability-manifest.mjs from contract/openapi.yaml — and the
// work spec "Client obligations and parity").
//
// Every OpenAPI operationId must appear in the generated manifest with exactly
// one disposition; every operation needs an agent reference entry; destructive,
// lifecycle, and designated sheet-management operations need a REACHABLE human
// control (an exported TypeScript function without a reachable control does
// not count as a human path); exemptions require explicit contract-author
// approval and a reason.
//
// The manifest landed in Wave 2 (SC-C5), so PARITY-MANIFEST-001,
// PARITY-AGENT-002, and PARITY-EXEMPT-004 are guards. PARITY-HUMAN-003 is
// green since Waves 4-7: the frontend exposes the required human controls
// (delete/retire/import/repair/end-of-score/end-of-downtime and the notebook
// editor), so the required human set is reachable.
// ---------------------------------------------------------------------------

const here = dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = resolve(here, "../../../skill/api-reference/capability-manifest.json");
const README_PATH = resolve(here, "../../../skill/api-reference/README.md");
const OPENAPI_PATH = resolve(here, "../../../contract/openapi.yaml");
const FRONTEND_SRC = resolve(here, "../../../frontend/src");

interface ManifestEntry {
  disposition: string;
  method: string;
  path: string;
  agentReference: string;
  flagged?: boolean;
}

interface Manifest {
  schemaVersion: number;
  generatedFrom: string;
  operationCount: number;
  dispositions: Record<string, ManifestEntry>;
  approvedExemptions: Array<Record<string, unknown>>;
}

/**
 * The required human set, per the work spec ("Client obligations and parity")
 * and the manifest generator's classification table:
 * destructive (3) + lifecycle (7) + data-management (2) + repair (4) +
 * designated sheet-management subset (7) + gated corrections (1,
 * CONTRACT-03 — DEC-03 ruling: reachable only behind the frontend
 * Enable-corrections toggle).
 */
const REQUIRED_HUMAN_OPS: readonly string[] = [
  "deleteCharacter", "deleteCrew", "deleteClock",
  "undoCharacter", "undoCrew", "endScore", "endDowntime", "retireCharacter", "traumaAdd", "traumaRemove",
  "importCharacter", "importCrew",
  "repairCharacterPreview", "repairCharacterApply", "repairCrewPreview", "repairCrewApply",
  "dossierUpdate", "noteAdd", "noteRemove", "notebookSet", "crewFieldsUpdate", "crewNoteAdd", "crewNoteRemove",
  "stressFix",
];

/** Runtime narrowing for JSON bodies: object and not an array. */
function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;
}

function asString(value: unknown): string | null {
  return typeof value === "string" ? value : null;
}

async function readManifest(): Promise<{ manifest: Manifest; operationIds: string[] }> {
  const manifest = JSON.parse(await readFile(MANIFEST_PATH, "utf8")) as unknown;
  const record = asRecord(manifest);
  if (record === null) throw new Error("capability manifest is not a JSON object");
  const { endpoints } = await parseOpenApi(OPENAPI_PATH);
  const operationIds = enumerateOperationIds(endpoints);
  return { manifest: record as unknown as Manifest, operationIds };
}

interface FunctionSpan {
  name: string;
  start: number;
  end: number;
}

/** Exported function spans of a TS source, in file order. */
function functionSpans(source: string): FunctionSpan[] {
  const spans: FunctionSpan[] = [];
  const markers: Array<{ index: number; name: string }> = [];
  const re = /export (?:async )?function ([A-Za-z0-9_]+)\s*\(/g;
  for (let match = re.exec(source); match !== null; match = re.exec(source)) {
    markers.push({ index: match.index, name: match[1] });
  }
  for (let i = 0; i < markers.length; i += 1) {
    spans.push({
      name: markers[i].name,
      start: markers[i].index,
      end: i + 1 < markers.length ? markers[i + 1].index : source.length,
    });
  }
  return spans;
}

function lastSegment(path: string): string {
  const trimmed = path.replace(/\/+$/, "");
  const slash = trimmed.lastIndexOf("/");
  return slash >= 0 ? trimmed.slice(slash + 1) : trimmed;
}

describe("capability parity (SC-O7)", () => {
  testCase(
    "PARITY-MANIFEST-001",
    "every operationId in the contract appears in the generated manifest with exactly one disposition",
    async () => {
      const { manifest, operationIds } = await readManifest();
      expect(manifest.schemaVersion).toBe(1);
      expect(manifest.generatedFrom).toBe("contract/openapi.yaml");
      expect(manifest.operationCount).toBe(operationIds.length);

      const dispositionKeys = Object.keys(manifest.dispositions).sort();
      expect(dispositionKeys, "manifest covers exactly the contract operationIds (no drift in either direction)").toEqual(
        [...operationIds].sort(),
      );
      for (const id of operationIds) {
        const entry = manifest.dispositions[id];
        expect(entry, `${id} has a disposition`).toBeDefined();
        if (entry === undefined) continue;
        expect(["agent", "human", "exempt"], `${id} disposition is one of agent|human|exempt`).toContain(entry.disposition);
        expect(entry.method, `${id} method`).toBeTypeOf("string");
        expect(entry.method.length).toBeGreaterThan(0);
        expect(entry.path, `${id} path`).toBeTypeOf("string");
        expect(entry.path.length).toBeGreaterThan(0);
      }
    },
  );

  testCase(
    "PARITY-AGENT-002",
    "every operation has an agent reference entry that resolves in the API reference",
    async () => {
      const { manifest, operationIds } = await readManifest();
      const readme = await readFile(README_PATH, "utf8");
      for (const id of operationIds) {
        const entry = manifest.dispositions[id];
        if (entry === undefined) continue;
        const reference = asString(entry.agentReference);
        expect(reference, `${id} agentReference present`).not.toBeNull();
        if (reference === null) continue;
        expect(reference, `${id} agentReference points at the API reference`).toMatch(/^api-reference\/README\.md#/);
        const anchor = reference.split("#").at(-1) ?? "";
        // GitHub-style slug of the operationId heading (`## getServiceCapabilities`
        // → #getservicecapabilities); headings are authored as `## <operationId>`.
        expect(anchor, `${id} anchor slug`).toBe(id.toLowerCase());
        expect(readme.includes(`## ${id}`), `${id} reference section exists (${reference})`).toBe(true);
      }
    },
  );

  testCase(
    "PARITY-HUMAN-003",
    "destructive, lifecycle, and sheet-management operations have reachable human routes",
    async () => {
      const { manifest, operationIds } = await readManifest();

      // The manifest must classify exactly the work-spec required human set.
      const humanOps = operationIds.filter((id) => manifest.dispositions[id]?.disposition === "human");
      expect([...humanOps].sort(), "manifest human set equals the required destructive/lifecycle/sheet set").toEqual(
        [...REQUIRED_HUMAN_OPS].sort(),
      );

      // Reachability evidence: an exported client function whose body performs
      // the operation, referenced from a page that (a) is mounted by a route in
      // main.ts and (b) wires an interactive control (addEventListener).
      const clientSource = await readFile(resolve(FRONTEND_SRC, "api", "client.ts"), "utf8");
      const mainSource = await readFile(resolve(FRONTEND_SRC, "main.ts"), "utf8");
      const spans = functionSpans(clientSource);

      const pageSources = new Map<string, string>();
      const pageImport = /\.\/pages\/([A-Za-z0-9-]+)\.js/g;
      for (let match = pageImport.exec(mainSource); match !== null; match = pageImport.exec(mainSource)) {
        const pageName = match[1];
        pageSources.set(pageName, await readFile(resolve(FRONTEND_SRC, "pages", `${pageName}.ts`), "utf8"));
      }
      expect(pageSources.size, "main.ts mounts at least one page").toBeGreaterThan(0);

      const missing: string[] = [];
      for (const id of humanOps) {
        const entry = manifest.dispositions[id];
        if (entry === undefined) continue;
        const segment = lastSegment(entry.path);
        // Client convention (work spec: the frontend consumes generated
        // metadata): the exported client function is named after the
        // operationId (undoCharacter, crewNoteAdd, deleteClock, ...). The
        // function body must also contain the operation's URL/op literal so a
        // same-named stub cannot pass.
        const span = spans.find((candidate) => candidate.name === id);
        if (span === undefined) {
          missing.push(`${id} (no client function ${id} for ${entry.method} ${entry.path})`);
          continue;
        }
        const needle = clientSource.includes(`"${segment}"`) ? `"${segment}"` : `/${segment}`;
        if (!clientSource.slice(span.start, span.end).includes(needle)) {
          missing.push(`${id} (client fn ${id} does not implement ${entry.path})`);
          continue;
        }
        const wired = [...pageSources.entries()].some(
          ([, source]) => source.includes(id) && source.includes("addEventListener"),
        );
        if (!wired) {
          missing.push(`${id} (client fn ${id} has no reachable control in a routed page)`);
        }
      }
      expect(missing, "human operations without a reachable human control").toEqual([]);
    },
  );

  testCase(
    "PARITY-EXEMPT-004",
    "manifest exemptions require explicit approval and a reason",
    async () => {
      const { manifest, operationIds } = await readManifest();
      const approved = manifest.approvedExemptions;
      expect(Array.isArray(approved), "approvedExemptions is an array").toBe(true);
      const entries = Array.isArray(approved) ? approved : [];

      const exemptOps = operationIds.filter((id) => manifest.dispositions[id]?.disposition === "exempt");
      for (const id of exemptOps) {
        const approval = entries.find((candidate) => asRecord(candidate)?.operationId === id);
        expect(approval, `${id} exemption is recorded in approvedExemptions`).toBeDefined();
        if (approval === undefined) continue;
        const reason = asString(asRecord(approval)?.reason);
        expect(reason, `${id} exemption has a reason`).not.toBeNull();
        if (reason !== null) expect(reason.trim().length).toBeGreaterThan(0);
        const approvedBy = asString(asRecord(approval)?.approvedBy);
        expect(approvedBy, `${id} exemption has an approver`).not.toBeNull();
        if (approvedBy !== null) expect(approvedBy.trim().length).toBeGreaterThan(0);
      }
      // No orphan approvals: every recorded exemption corresponds to a manifest
      // disposition of "exempt".
      for (const approval of entries) {
        const id = asString(asRecord(approval)?.operationId);
        expect(id, "approval names an operation").not.toBeNull();
        if (id !== null) expect(exemptOps, `approval for ${id} matches an exempt disposition`).toContain(id);
      }
    },
  );
});
